name = "MyFirstPackage"
uuid = "25c887bc-ae56-41f8-9368-730d8d370e9d"
authors = ["Huanhai Zhou"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
